### PR TITLE
Integrate anynines first version of the docs

### PR DESCRIPTION
**Pull request by lucaspinto**
This PR consists of 3 mains changes:

- we created the content of the documentation of the tile
- I remove the  docs-book/output/ path from the repo as it is useless
- we made changes in the configuration

Cheers,
Lucas

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @lucaspinto ! We'll take a look.

**Comment by jncd** [comment]
Hello @lucaspinto 
The doc looks good. I edited the using page of the doc to make to it procedural — made steps to make it clear what the developers have to _do_. 
I have more questions about the installing page. The first part is a very clear procedure, but then it turns into reference material... the numbered steps go away. 
I just want to make sure that means there are no configuration steps that the operator _has_ to do to get a9s Elasticsearch working in a vanilla system.  
Are you planning a troubleshooting page that will link back to this reference material? 
For example, the doc says "You _can_ configure the dimensions of VMs..." but it doesn't say why or when you would do this. 
TIA, Jane

**Comment by gogolok** [comment]
Hey @jncd 
Maybe we should create an issue for your feedback/suggestions? Someone from our team can pick the issue, work on it and create incremental PRs for example.

**Comment by jncd** [comment]
Very good idea. Done!

**Pull request merged**
